"use client";
import DashboardCard from "@/components/dashboard/DashboardCard";
import { api } from "@/api/api";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { CircleDollarSign, ClipboardList, Users } from "lucide-react";

// export const metadata = {
//   title: "Admin Dashboard",
//   description: "Generated by create next app",
// };
export default function Home() {
  const [employees, setEmployees] = useState(0);
  const [attendances, setAttendances] = useState(0);
  const [salaries, setSalaries] = useState(0);
  const getCount = async () => {
    try {
      //fetch employee from api
      const fetchEmployee = await api.get("api/employee/v1/getAllEmployee");
      const employeeData = fetchEmployee.data.totalCount;
      setEmployees(employeeData);

      const fetchAttendance = await api.get(
        "/api/attendance/v1/getAttendance/"
      );
      //fetch attendance from api
      const attendanceData = fetchAttendance.data.totalCount;
      setAttendances(attendanceData);

      //fetch salary from api
      const fetchSalary = await api.get("/api/salary/v1/getAllSalary/");
      const salaryData = fetchSalary.data.totalCount;
      setSalaries(salaryData);
    } catch (e) {
      toast.error("Error fetching pages");
    }
  };
  useEffect(() => {
    getCount();
  }, []);
  return (
    <>
      <div className="flex flex-col md:flex-row justify-evenly mb-5">
        <DashboardCard
          title="Employees"
          count={employees}
          icon={<Users className="text-slate-700" size={72} />}
        />
        <DashboardCard
          title="Attendances"
          count={attendances}
          icon={<ClipboardList className="text-slate-700" size={72} />}
        />
        <DashboardCard
          title="Salaries"
          count={salaries}
          icon={<CircleDollarSign className="text-slate-700" size={72} />}
        />
      </div>
    </>
  );
}
